name: Run Lilypad Job

on:
  issues:
    types: [opened, edited]

jobs:
  run_job:
    runs-on: ubuntu-latest
    if: github.event.issue.title == 'Run Lilypad Job'    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set OSARCH and OSNAME
        run: |
          OSARCH=$(uname -m | awk '{if ($0 ~ /arm64|aarch64/) print "arm64"; else if ($0 ~ /x86_64|amd64/) print "amd64"; else print "unsupported_arch"}')
          echo "OSARCH=$OSARCH" >> $GITHUB_ENV
          OSNAME=$(uname -s | awk '{if ($1 == "Darwin") print "darwin"; else if ($1 == "Linux") print "linux"; else print "unsupported_os"}')
          echo "OSNAME=$OSNAME" >> $GITHUB_ENV

      - name: Download Lilypad
        run: |
          curl https://api.github.com/repos/lilypad-tech/lilypad/releases/latest | grep "browser_download_url.*lilypad-$OSNAME-$OSARCH-cpu" | cut -d : -f 2,3 | tr -d \" | wget -i - -O lilypad

      - name: Install Lilypad
        run: |
          chmod +x lilypad
          sudo mv lilypad /usr/local/bin/lilypad

      - name: Run Lilypad job
        env:
          WEB3_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: lilypad --network demonet run cowsay:v0.0.4 -i Message="hello, lilypad"